apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: transplantdb-deployment
  annotations:
    app.gitlab.com/app: <CI_PROJECT_PATH_SLUG>
    app.gitlab.com/env: <CI_ENVIRONMENT_SLUG>
  namespace: eg-static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transplantdb
        RUP: nickl
    spec:
      containers:
      - name: transplantdb-deployment
        image: dockerhub.ebi.ac.uk/kamal/transplantdb-static:<VERSION>
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: eg-transplantdb-pull-secrets